### ISSUE TITLE
Add stop with MetricDimensionValues parameter to Stopwatch interface

### ISSUE THREAD

**Issue by mairovichaa** [ringcentral/metrics-facade#5]
Let's consider the following case:

```
    public static void main(String[] args) throws InterruptedException {
        DropwizardMetricRegistry registry = new DropwizardMetricRegistry();

        MetricDimension statusDimension = new MetricDimension("status");

        Timer timer = registry.timer(
                withName("timer"),
                () -> withTimer().dimensions(statusDimension)
        );
        
        Stopwatch stopwatch = timer.stopwatch();
        try {
            operation();
            stopwatch.stop(dimensionValues(statusDimension.value("success")));
        } catch (ExceptionInInitializerError ex) {
            stopwatch.stop(dimensionValues(statusDimension.value("failure")));
        }
    }
```

At the moment of `stopwatch`'s creation value of `statusDimension` isn't known.

So in this case it's not possible to use Stopwatch and a need to use some custom solution appears.

However stop with  `MetricDimensionValues dimensionValues` parameter seems to fit naturally.

I suggest to add it.

ps:
In my opinion , dimensionValues has to be passed to Stopwatch instance only once.

The second attempt should lead to exception.
For example, 
```
        Stopwatch stopwatch = timer.stopwatch(dimensionValues(statusDimension.value("success")));
        operation();
        // an exception should be thrown
        stopwatch.stop(dimensionValues(statusDimension.value("fatal")));
```

**Comment by devromik** [comment]
> However stop with MetricDimensionValues dimensionValues parameter seems to fit naturally. 
I suggest to add it.

This is a good point. We'll add it. :) 

> ps:
In my opinion , dimensionValues has to be passed to Stopwatch instance only once.
The second attempt should lead to exception.

+, we'll implement it.
